# Comment out the old Splunk Enterprise Server security key using 'replace' module.
- name: Update 'server.conf' file with commending out [general] key.
  replace: 
    path: /opt/splunk/etc/system/local/server.conf
    regexp: '(.*pass4SymmKey.*)'
    replace: '#\1'
  when: inventory_hostname in groups['splunk_sh_deployer']

# Set new security key for the Splunk Enterprise Search Head Cluster using 'blockinfile' module.
- name: Update 'server.conf' file with search head [shclustering] key.
  blockinfile:
    path: /opt/splunk/etc/system/local/server.conf
    block: |
      [shclustering]
      pass4SymmKey = "{{ splunk_deployer_key }}"
      shcluster_label = "{{ splunk_sh_label }}"
    marker: no
  when: inventory_hostname in groups['splunk_sh_deployer']




