- name: Initialize Splunk Search Head Node 001
  shell: |
    /opt/splunk/bin/splunk init shcluster-config -auth admin:G00m-WOW! -mgmt_uri "{{ splunk_sh_001_url }}":8089 -replication_port 34567 -replication_factor 3 -conf_deploy_fetch_url "{{ splunk_deployer_url }}":8089 -secret G00m-WOW! -shcluster_label "{{ splunk_sh_label }}"
    /opt/splunk/bin/splunk restart
  when: "'sh-001' in inventory_hostname"

- name: Initialize Splunk Search Head Node 002
  shell: |
    /opt/splunk/bin/splunk init shcluster-config -auth admin:G00m-WOW! -mgmt_uri "{{ splunk_sh_002_url }}":8089 -replication_port 34567 -replication_factor 3 -conf_deploy_fetch_url "{{ splunk_deployer_url }}":8089 -secret G00m-WOW! -shcluster_label "{{ splunk_sh_label }}"
    /opt/splunk/bin/splunk restart
  when: "'sh-002' in inventory_hostname"

- name: Initialize Splunk Search Head Node 003
  shell: |
    /opt/splunk/bin/splunk init shcluster-config -auth admin:G00m-WOW! -mgmt_uri "{{ splunk_sh_003_url }}":8089 -replication_port 34567 -replication_factor 3 -conf_deploy_fetch_url "{{ splunk_deployer_url }}":8089 -secret G00m-WOW! -shcluster_label "{{ splunk_sh_label }}"
    /opt/splunk/bin/splunk restart
  when: "'sh-003' in inventory_hostname"

- name: Sleep for 30 seconds and wait for Cluster Node 001 to start
  wait_for:
    timeout: 30

- name: Make Splunk Search Head Node 001 Cluster Captain
  shell: |
    /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "{{ splunk_sh_001_url }}:8089,{{ splunk_sh_002_url }}:8089,{{ splunk_sh_003_url }}:8089" -auth admin:G00m-WOW!
  when: "'sh-001' in inventory_hostname"
